[tool.poetry]
name = "lab"
version = "0.1.0"
description = ""
authors = ["Andrew Bates <andrew.bates@networktocode.com>"]

[tool.poetry.dependencies]
python = "^3.9"
invoke = "^1.7.1"
cookiecutter = "^2.1.1"
pexpect = "^4.8.0"
shellingham = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
