---
services:
  awx:
    depends_on: 
      awx-db:
        condition: service_healthy
    image: "ghcr.io/abates/nautobot-labs-awx:21.9.0"
    command: launch_awx.sh
    environment:
      RUN_MIGRATIONS: 1
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label:disable
    tty: true
    devices:
      - /dev/fuse:/dev/fuse
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8052"  # http
  awx-redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_REDIS_PASSWORD from the env
      - "redis-server --appendonly yes"
  awx-db:
    image: postgres:12
    command: postgres -c log_destination=stderr -c log_min_messages=info -c log_min_duration_statement=1000 -c max_connections=1024
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: awx
      POSTGRES_DB: awx
      POSTGRES_PASSWORD: shuOKNHPUwtxdxjNjMoZ
    volumes:
      - "awx_db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "awx"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  awx_db:
    name: tools_awx_db
  redis_socket_1:
    name: tools_redis_socket_1
