---
version: "3.8"

services:
  git_server:
    build:
      context: "git_server"
      dockerfile: "./Dockerfile"
    volumes:
      - "git_server_repos:/internal/repos"

volumes:
  git_server_repos: {}
